FROM python:3-slim AS build-env
COPY ./app /app
WORKDIR /app
RUN pip install -r requirements.txt

FROM gcr.io/distroless/python3
COPY --from=build-env /app /app
COPY --from=build-env /usr/local/lib/python3.10/site-packages /usr/local/lib/python3.10/site-packages
WORKDIR /app
ENV PYTHONPATH=/usr/local/lib/python3.10/site-packages
EXPOSE 5000
CMD ["main.py"]